### ISSUE TITLE
Sourcify has migrated from IPNS to DNSLink

### ISSUE THREAD

**Issue by sambacha** [wmitsuda/topic0#2]
## Migrate to using DNSLink from IPNS
I would open a PR but I am not sure how you want to handle this 

[ref changes https://github.com/ethereum/sourcify/commit/1e33e676389f39957bcb00d60e575ad024f10750](https://github.com/ethereum/sourcify/commit/1e33e676389f39957bcb00d60e575ad024f10750)

### Stable
```ini
IPNS=k51qzi5uqu5dll0ocge71eudqnrgnogmbr37gsgl12uubsinphjoknl6bbi41p
```

```diff
- IPNS=k51qzi5uqu5dll0ocge71eudqnrgnogmbr37gsgl12uubsinphjoknl6bbi41p

+ IPNS=repo.sourcify.dev # Use DNSLink
```

### Staging

```ini
IPNS=k51qzi5uqu5dkuzo866rys9qexfvbfdwxjc20njcln808mzjrhnorgu5rh30lb
```

```diff
- IPNS=k51qzi5uqu5dkuzo866rys9qexfvbfdwxjc20njcln808mzjrhnorgu5rh30lb

+ IPNS=repo.staging.sourcify.dev # Use DNSLink
```

```shell
ipfs resolve -r /ipns/repo.sourcify.dev/manifest.json

**Comment by wmitsuda** [comment]
Oh right, you mean the docs here on github? I can update them, but it's ok to continue using the raw ipns name, it is only another user friendlier pointer to IPNS.

DNS -> IPNS -> IPFS

BTW, it was me who suggested them to create a dnslink, I just forgot to update the docs here 😅

**Comment by wmitsuda** [comment]
Closing, I think all references to raw IPNS were replaced by DNSLink.
